config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/tos'

  root 'home#index'
  get '/auth/twitter/callback', to:       'sessions#create'
  delete '/logout',             to:       'sessions#destroy'
  
  resources :eateries do
    resources :items 
  end
  resources :searches

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :eateries
  validates_presence_of :name
end

app/models/eatery.rb
class Eatery < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  belongs_to :category
  has_many :eatery_items
  has_many :items, through: :eatery_items
  has_attached_file :eatery_img, 
    styles: { eatery_index: "250x350>", eatery_show: "325x475>" },
    default_url: "missing.png"
  validates_attachment_content_type :eatery_img, content_type: /\Aimage\/.*\z/
  validates_numericality_of :rating, in: 1..5
  validates_numericality_of :price_range, in: 1..5
  validates_presence_of :name, :address, :lat, :long

  def self.search(search)
    if search.present?
      where(["name LIKE ?","%#{search}%"])
    else
      all
    end
  end

  def self.filter(category)
    where(category: category).order('created_at DESC')
  end
end

app/models/eatery_item.rb
class EateryItem < ActiveRecord::Base
  belongs_to :eatery
  belongs_to :item
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :eatery_items
  has_many :eateries, through: :eatery_items
  has_attached_file :item_image, styles: { item_medium: "300x300>", item_thumb: "100x100>" }, 
    default_url: "missing.png"
  validates_attachment_content_type :item_image, content_type: /\Aimage\/.*\z/
  validates_presence_of :name, :description
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :name, :provider, :uid, :location, :image_url, :url
  
  class << self
    def from_omniauth(auth_hash)
      user = find_or_create_by(uid: auth_hash['uid'], provider: auth_hash['provider'])
      user.name = auth_hash['info']['name']
      user.location = auth_hash['info']['location']
      user.image_url = auth_hash['info']['image']
      user.url = auth_hash['info']['urls']['Twitter']
      user.save!
      user
    end
  end

  def super_admin?
    role_type 'SUPERADMIN'
  end

  def eatery_admin?
    role_type 'EATERYADMIN'
  end

  private

  def role_type(role_type)
    return true if role.eql? role_type
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  helper_method :current_user

  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def redirecting_action
    observable_redirect_to('https://software-part-2-vaibhavacharya.c9users.io/eateries')
  end
  
  def integration_test?
    Rails.env.test? && defined?(Cucumber::Rails)
  end

  def redirect_to_twitter_preapproval(key)
  redirect_to URI.encode("#{Rails.configuration.twitter.preapproval_link}#{key}") 
  end

  def observable_redirect_to(url)
    if integration_test?
      render :text => "If this wasn't an integration test, you'd be redirected to: #{url}"
    else
      redirect_to url
    end
  end

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || stored_location_for(resource) || root_path
  end


end

app/controllers/eateries_controller.rb
class EateriesController < ApplicationController
  before_action :find_eatery, only: [:show, :edit, :update, :destroy] 

  def index
    redirect_to root_path unless current_user
    if params[:category].blank?
      @eateries = Eatery.search(params[:search])
    else
      category = Category.find_by(name: params[:category]).id
      eateries = Eatery.search(params[:search])
      @eateries = eateries.filter(category)
    end
  end

  def show
  end

  def new
    @eatery = Eatery.new
    @categories = Category.all.map { |c| [c.name, c.id] }
  end

  def create
    @eatery = Eatery.new(eatery_params)
    respond_to do |format|
      if @eatery.save
        format.html { redirect_to root_path, notice: 'eatery was successfully created.' }
        format.json { render :show, status: :created, location: @eatery }
      else
        format.html { render :new }
        format.json { render json: @eatery.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @categories = Category.all.map { |c| [c.name, c.id] }
  end

  def update
    if @eatery.update(eatery_params)
      redirect_to eatery_path(eatery_params)
    else
      render 'edit'
    end
  end
 
  def destroy
    redirect_to root_path if @eatery.destroy
  end


  private
  
  def eatery_params 
    params.require(:eatery).permit(:name, :address, :category_id, :eatery_img, :lat, :long) 
  end

  def find_eatery
    @eatery = Eatery.friendly.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to eateries_path if current_user
  end
  
 

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  layout "eateries"

  def index 
    @eatery = Eatery.friendly.find(params[:eatery_id])
    @items = @eatery.items.order('name DESC')
    @eatery_item = Item.new
  end

  def new
    @eatery = Eatery.friendly.find(params[:eatery_id])
    @eatery_item = Item.new
  end

  def create
    eatery_item = Item.find_or_create_by(name: item_params[:name], 
      description: item_params[:description])
    eatery_item.item_image = params[:item]['item_image']
    eatery_item.save!
    eatery = Eatery.friendly.find(params[:eatery_id])
    eatery.items << eatery_item
    redirect_to eatery_items_path(eatery)
  end

  private

  def item_params 
    params.require(:item).permit(:name, :description, :eatery_id, :item_image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    begin
      @user = User.from_omniauth(request.env['omniauth.auth'])
      session[:user_id] = @user.id
      flash[:success] = "Welcome, #{@user.name}!"
    rescue
      flash[:warning] = "There was an error while trying to authenticate you..."
    end

    redirect_to eateries_path
  end

  def destroy
    if current_user
      session.delete(:user_id)
      flash[:success] = 'Hope you had a good time. See You Again Soon!'
    end
    redirect_to root_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def tos
    render layout: "eateries"
  end
end

app/views/eateries/_form.html.haml
= form_for(@eatery) do |f|
  - if @eatery.errors.any?
    #error_explanation
      %h2
        = pluralize(@eatery.errors.count, "error")
        prohibited this eatery from being saved:
      %ul
        - @eatery.errors.full_messages.each do |message|
          %li= message
  .form-group.field
    = f.text_field :name, class: 'form-control', placeholder: :name
  .form-group.field
    = f.text_field :address, class: 'form-control', placeholder: :address
  .form-group.field
    = f.label :image
    = f.file_field :eatery_img, class: 'form-control'
  .form-group.field
    = f.label 'Category of the eatery:'
    = f.select(:category_id, options_for_select(@categories), { include_blank: "Select a category" }, {class: 'selectpicker'})
  .form-group.info.float-right.h5
    = f.label '#IMP: Click to select Latitude, Longitude from map before or enter values before save.'
    %br/
  .form-group
    = f.label :latitude
    = f.text_field :lat, class: 'form-control'
    %br/
    = f.label :longitude
    = f.text_field :long, class: 'form-control'
  .form-group.actions
    = button_tag class: 'btn btn-success' do
      %i.fa.fa-save
      &nbsp;&nbsp;Save&nbsp;&nbsp;

app/views/eateries/_sidebar.html.haml
/ sidebar start
%aside
  #sidebar.nav-collapse
    / sidebar menu start
    %ul#nav-accordion.sidebar-menu
      %p.centered
        %a{:href => "profile.html"}
        - if current_user.image_url
          = image_tag current_user.image_url, class: 'avatar img-circle', alt: current_user.name
      %h5.centered= current_user.name
      
      %li.mt
      %li.sub-menu
        = link_to eateries_path, |
          class: "#{'active' unless params[:category] }"  do
          %i.fa.fa-eercast
          List All

      - Category.all.each do |cat|
        %li.sub-menu
          = link_to eateries_path(search: params[:search], category: cat.name), |
            class: "#{'active' if params[:category] == cat.name }", 
            method: :get do
            %i.fa{ class: "fa-#{FA_ICO_MAP[cat.name]}" }
            = cat.name

      - if current_user.super_admin?
        %li.sub-menu
          %a{:href => "javascript:;"}
            %i.fa.fa-user-secret
            %span ADMIN PANEL
          %ul.sub
            %li
              = link_to 'Create Eatery', new_eatery_path

      %li.sub-menu.logout
        = link_to logout_path, method: :delete do
          %i.fa.fa-sign-out
          LOG OUT &emsp;
          
    / sidebar menu end
/ sidebar end

app/views/eateries/edit.html.haml
.container.top-100
  .span12
    .row
      %h2.text-center.headerRibbon
        = "Edit details of #{@eatery.name}"
      .col-sm-6
        = render 'form'
        .form-group
          = link_to eateries_path, method: :get, class: 'btn btn-array btn-primary' do
            %i.fa.fa-backward
            &nbsp;Back&nbsp;
          = link_to new_eatery_path, class: 'btn btn-array btn-info' do
            %i.fa.fa-plus
            &nbsp;Create&nbsp;
          = link_to eatery_path(@eatery), method: :delete, data: { confirm: "Are you sure?"}, class: 'btn btn-danger btn-array' do
            %i.fa.fa-trash
            &nbsp;Delete&nbsp;
          = link_to eatery_items_path(@eatery), method: :get, class: 'btn btn-warning btn-array' do
            %i.fa.fa-tasks
            &nbsp;Manage Items&nbsp;
      .col-sm-6
        .form-group.float-right
          .map#map.mapNewAdd

app/views/eateries/index.html.haml
%header.header.black-bg
  / logo start
  / = link_to 'BingBites', root_path, class: 'navbar-brand'
  / logo end
  .top-menu
    %ul.nav.pull-right.top-menu
    .header.row
      #logoBingBites
        = image_tag "pic01.jpg"
      / %span.logoBingBites BingBites
      = form_tag(eateries_path, method: "get", id: "search-form") do
        - if params[:category] 
          = text_field_tag 'search', nil, placeholder: "Looking for #{params[:category].titleize} cuisine today?", |
            class: 'searchBar'
          = hidden_field_tag 'category', params[:category]
        - else
          = text_field_tag 'search', nil, placeholder: 'Start searching best hangout places around you...', |
            class: 'searchBar'
    
      #location.location
        %i.fa.fa-compass
        Geolocating...
      .headerLinks  
        = link_to '#' do  
          %i.fa.fa-fort-awesome 
          Events
        = link_to '#' do  
          %i.fa.fa-free-code-camp
          Nightlife
        = link_to '#' do  
          %i.fa.fa-ils
          New Listing
        = link_to '#' do  
          %i.fa.fa-dot-circle-o
          Trending
        = link_to '#' do  
          %i.fa.fa-btc
          Deals
        = link_to '#' do  
          %i.fa.fa-car
          Drive Thru

= render 'sidebar'

.wrapper
- if @eateries.count == 0
  .listingEateries
    .row.mt
      .nothingFound
        %h1 There are no eateries available yet, our team is setting up things to bring you some.
- else
  .listingEateries
    .row.mt
      - @eateries.each do |eatery|
        .col-md-4.col-sm-4.mb
          .white-panel.pn
            .blog-bg
              = link_to eatery do  
                = image_tag eatery.eatery_img.url(:eatery_index), class: 'eateryImg'
              .cuisineCategory
                =  eatery.category ? eatery.category.name : 'Misc'
              .white-header.titleImg
                = link_to eatery.name.upcase, eatery_path(eatery),
                class: 'eateryTitle'
                .address
                  = eatery.address.slice(0, 30) 
              - if eatery.rating > 0
                .ratings
                  = eatery.rating
                  %i.fa.fa-heart
              - if eatery.price_range > 0
                .priceRange
                  - eatery.price_range.times do
                    %i.fa.fa-usd 
              .showBackground{style: "background-image: url(#{eatery.eatery_img.url});"}
          / = image_tag ea.book_img.url(:book_index), class: "book"
/ Footer
%footer#footer
  %ul.icons
    %li
      %a.icon.alt.fa-twitter{:href => "#"}
        %span.label Twitter
    %li
      %a.icon.alt.fa-facebook{:href => "https://www.facebook.com/BingBites-737339629772865/"}
        %span.label Facebook
    %li
      %a.icon.alt.fa-linkedin{:href => "#"}
        %span.label LinkedIn
    %li
      %a.icon.alt.fa-instagram{:href => "https://www.instagram.com/bingbites"}
        %span.label Instagram
    %li
      %a.icon.alt.fa-github{:href => "https://github.com/BingBites/bingbites"}
        %span.label GitHub
    %li
      %a.icon.alt.fa-envelope{:href => "#"}
        %span.label Email
  %ul.copyright
    %li © BingBites 
    %li All rights reserved.
    %li 
      = link_to 'Terms of Service', static_pages_tos_path

app/views/eateries/new.html.haml
.container.top-100.center
  .span12
    .row
      %h2.text-center.headerRibbon
        Create New Eatery
      .col-sm-6
        = render 'form'
        .form-group
          = link_to eateries_path, method: :get, class: 'btn btn-primary' do
            %i.fa.fa-backward
            &nbsp;Back&nbsp;
      .col-sm-6
        .form-group.float-right
          .map#map.mapNewAdd

app/views/eateries/show.html.haml
.blog-bg.showTitleHeader
  .white-header.titleHeaderShow
    .showBackground{style: "background-image: url(#{@eatery.eatery_img.url});"}
    %h3.showTitle
      %strong= @eatery.name.upcase
    %h3.form-group.showSubTitle
      We are located at, 
      %strong= @eatery.address
    %h4.form-group.showCategory
      Cuisine we serve, 
      %strong= @eatery.category ? @eatery.category.name.titleize : 'No Category'
    .traversal
      = link_to root_path, method: :get, class: 'btn btn-array btn-primary' do
        %i.fa.fa-backward
        &nbsp;Back&nbsp;
      - if current_user.super_admin?
        = link_to edit_eatery_path(@eatery), class: 'btn btn-array btn-warning' do
          %i.fa.fa-edit
          &nbsp;Edit&nbsp;
        = link_to eatery_path(@eatery), method: :delete, data: { confirm: "Are you sure?"},
          class: 'btn btn-danger btn-array' do
          %i.fa.fa-trash
          &nbsp;Delete&nbsp;
  .itemsListing
    - unless @eatery.items.blank?
      .itemsHeader
        Excluive Listing Just For You
      %ul.items
        - @eatery.items.each do |e|
          %li
            .itemImage
              = image_tag e.item_image.url(:item_medium), class: 'eateryItemImg'
            .itemName
              = e.name
            .itemDescription
              - if e.description.length < 160
                = e.description
              - else
                = "#{e.description.first(160)}..."
    - else
      .itemName.notFound
        .notFoundHeader
          = "Duh! No food here."
        .notFoundDescription
          = "Worry not. Our team is working hard to bring you some. Meanwhile  please head to some of the exciting listings that we have on file, just for you :)"
        .notFoundLinks
          = link_to "Discover more of fine dining around.", root_path 
        
  .latLong
    = { lat: @eatery.lat, long: @eatery.long }.to_json 
  .form-inline
    .showMap#map
 
      

app/views/home/index.html.haml
/ Banner
%section#banner
  .content
    %header
      %h2 BingBites
      %p
        Just food. Loads of lip licking Delicacies, Happiness.
        %br/
        There are no hoverboards or flying cars around.
        %br/
        Yet there's an easy way to find quick-lunch.
    %span.image
      = image_tag "pic0x.jpg"
  %a.goto-next.scrolly{:href => "#one"} Next

/ One
%section#one.spotlight.style1.bottom
  %span.image.fit.main
    = image_tag "pic02.jpg"
  .content
    .container
      .row
        .4u{:class => "12u$(medium)"}
          %header
            %h2 Welcome to BingBites
            %p
              Stay hungry. Stay foolish
              %br/
              So how it works ?
        .4u{:class => "12u$(medium)"}
          %ul
            %li SignIn to search the restaurants
            %li Pick the restaurant from the list
            %li Choose from the available categories
            %li Browse exhaustive list of cousines
            %li Find out Specialities Served for the day
            %li Review what you liked and what you didn't
        %div{:class => "4u$ 12u$(medium)"}
          %p
            We are trying to redefine how you search for food
            in the locality. Our goal is to serve you delicious
            food with events and seasonal specialties.
            %br/
            Do you love pleasant ambiance and peculiar meal
            that matches your taste of food for your mood?
            BingBites finds it for you at your fingertips.


  %a.goto-next.scrolly{:href => "#two"} Next
/ Two
%section#two.spotlight.style2.right
  %span.image.fit.main
    = image_tag "pic03.jpg"
  .content
    %header
      %h2 Enabling restaurants to create amazing experiences.
      %p Every restaurant we listed is a speciality in itself providing services to bring you delight.
    %p With dedicated engagement and collaboration tools, we're enabling restaurants to spend more time focusing on food itself, which translates directly to better dining experiences.
    %ul.actions
      %li
        %a.button{:href => "#"} Learn More
  %a.goto-next.scrolly{:href => "#three"} Next
/ Three
%section#three.spotlight.style3.left
  %span.image.fit.main.bottom
    = image_tag "pic04.jpg"
  .content
    %header
      %h2 Helping people discover great places around them.
      %p Building amazing experiences around dining.
    %p Our team gathers information from every restaurant on a regular basis to ensure our data is fresh. Our vast community of food lovers share their reviews and photos, so you have all that you need to make an informed choice.
    %ul.actions
      %li
        %a.button{:href => "#"} Learn More
  %a.goto-next.scrolly{:href => "#four"} Next
/ Four
%section#four.wrapper.style1.special.fade-up
  .container
    %header.major
      %h2 The Team
      %p
        We are
        = succeed "," do
          %code Coders
        Fun People,
        = succeed "," do
          %code Geeks
        Party Animals
    .box.alt
      .row.uniform
        %section.4u{:class => "6u(medium) 12u$(xsmall)"}
          %span.icon.alt.major.fa-gg-circle
          %h3 Suyog Nerkar
          %p
            %a.no-decoration{:href => "http://github.com/suyogrnerkar"}
              %span.label THE CHIEF MONK @ GITHUB
        %section.4u{:class => "6u$(medium) 12u$(xsmall)"}
          %span.icon.alt.major.fa-comment
          %h3 Debashish Majumdar
          %p Feugiat accumsan lorem e
        %section{:class => "4u$ 6u(medium) 12u$(xsmall)"}
          %span.icon.alt.major.fa-flask
          %h3 Pranav Garje
          %p Florem eu ac lorem amet accumsan
        %section.3u{:class => "6u$(medium) 12u$(xsmall)"}
          %span.icon.alt.major.fa-paper-plane
          %h3 Abhijit Bhandarkar
          %p accumsan donec. Blandit orci porttitor.
        %section.3u{:class => "6u(medium) 12u$(xsmall)"}
          %span.icon.alt.major.fa-file
          %h3 Vaibhav Acharya
          %p rci porttitor.
        %section.3u{:class => "6u(medium) 12u$(xsmall)"}
          %span.icon.alt.major.fa-file
          %h3 Uddhav Mhatre
          %p dit orci porttitor.
        %section{:class => "3u$ 6u$(medium) 12u$(xsmall)"}
          %span.icon.alt.major.fa-lock
          %h3 Kiran Kadam
          %p donec. Blandit orci porttitor.
    %footer.major
      %ul.actions
        %li
          %a.button{:href => "#"} Know More
/ Five
%section#five.wrapper.style2.special.fade
  .container
    %header
      %h2 Get started with BingBites, Absolutely Free !
      %p Enter your email to get sign up.
    %form.container{:action => "#", :class => "50%", :method => "post"}
      .row.uniform{:class => "50%"}
        .8u{:class => "12u$(xsmall)"}
          %input#email{:name => "email", :placeholder => "Your Email Address", :type => "email"}/
        %div{:class => "4u$ 12u$(xsmall)"}
          %input.fit.special{:type => "submit", :value => "Get Started"}/
/ Footer
%footer#footer
  %ul.icons
    %li
      %a.icon.alt.fa-twitter{:href => "#"}
        %span.label Tweets
    %li
      %a.icon.alt.fa-facebook{:href => "https://www.facebook.com/BingBites-737339629772865/"}
        %span.label Facebook
    %li
      %a.icon.alt.fa-linkedin{:href => "#"}
        %span.label LinkedIn
    %li
      %a.icon.alt.fa-instagram{:href => "https://www.instagram.com/bingbites"}
        %span.label Instagram
    %li
      %a.icon.alt.fa-github{:href => "https://github.com/BingBites/bingbites"}
        %span.label GitHub
    %li
      %a.icon.alt.fa-envelope{:href => "#"}
        %span.label Email
  %ul.copyright
    %li © BingBites. All rights reserved.
/ Scripts
/[if lte IE 8] <script src="assets/js/ie/respond.min.js"></script>

app/views/items/_form.html.haml
= form_for [@eatery, @eatery_item] do |f|
  - if @eatery_item.errors.any?
    #error_explanation
      %h2
        = pluralize(@eatery_item.errors.count, "error")
        prohibited this eatery_item from being saved:
      %ul
        - @eatery_item.errors.full_messages.each do |message|
          %li= message
  .form-group.field
    = f.text_field :name, class: 'form-control', placeholder: :name
  .form-group.field
    = f.text_field :description, class: 'form-control', placeholder: :description
  .form-group.field
    = f.label :image
    = f.file_field :item_image, class: 'form-control'
  / .form-group.field
  /   = f.label 'Category of the eatery_item:'
  /   = f.select(:category_id, options_for_select(@categories), { include_blank: "Select a category" }, {class: 'selectpicker'})
  .form-group.actions
    = button_tag class: 'btn btn-success' do
      %i.fa.fa-save
      &nbsp;&nbsp;Save&nbsp;&nbsp;
  .form-group
    = link_to eateries_path, method: :get, class: 'btn btn-primary' do
      %i.fa.fa-backward
      &nbsp;Back&nbsp;

app/views/items/edit.html.haml
.container.top-100.center
  .span12
    .row
      %h2.text-center.headerRibbon
        Create New Item
      .col-sm-6
        = render 'form'
        .form-group
          = link_to eateries_path, method: :get, class: 'btn btn-primary' do
            %i.fa.fa-backward
            &nbsp;Back&nbsp;

app/views/items/index.html.haml
.itemsListing.manageListing
  - unless @items.blank?
    .itemsHeader
      = "Manage Items for #{@eatery.name}"
    %ul.items
      - @items.each do |item|
        %li
          .itemImage
            = image_tag item.item_image.url(:item_medium), class: 'eateryItemImg'
          .itemName
            = item.name
          .itemDescription
            = item.description
  - else
    .itemsHeader
      = "Manage Items for #{@eatery.name}"
    %ul.items.noItemsFound
      %li
        No items yet.

  .addNewItem
    %h2.text-center.headerRibbon.createNewItem
      Create New Item
    = render 'form'

app/views/layouts/application.html.haml
- if params[:controller] = 'home'
  = render layout: 'home'
- else
  = render layout: 'eateries'

app/views/layouts/eateries.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BingBites
    = favicon_link_tag 'pic01.jpg'
    / = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag 'application-eateries', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag "https://api.mapbox.com/mapbox.js/v3.0.1/mapbox.css"
    = stylesheet_link_tag 'https://api.tiles.mapbox.com/mapbox-gl-js/v0.34.0/mapbox-gl.css'
    = stylesheet_link_tag 'https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v2.1.0/mapbox-gl-geocoder.css'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .clearfix
    %body
      #page-wrapper
        .row
          - flash.each do |key, value|
            %div{:class => "alert alert-#{key}"}
              = value
        = yield
    = javascript_include_tag 'https://api.mapbox.com/mapbox.js/v3.0.1/mapbox.js'
    = javascript_include_tag 'https://api.tiles.mapbox.com/mapbox-gl-js/v0.34.0/mapbox-gl.js'
    = javascript_include_tag 'https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v2.1.0/mapbox-gl-geocoder.min.js'
    = javascript_include_tag  'maps'

app/views/layouts/home.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BingBites
    = favicon_link_tag 'favicon.ico'
    / = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag 'application-homepage', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .clearfix
    %body.landing
      #page-wrapper
        / Header
        - flash.each do |key, value|
          %div{:class => "alert alert-homepage alert-#{key} "}
            = value
        %header#header
          %h1#logo
            = link_to 'BingBites', root_path
          %nav#nav
            %ul
              %li
                Sign In with &nbsp;
                - if current_user
                  = link_to 'Log Out', '/logout', class: 'button special twitter', method: :delete
                - else
                  = link_to '/auth/twitter', class: 'button special twitter',  id: 'twitter' do
                    Twitter
                    %i.fa.fa-sign-in
        = yield